# Generated by Django 4.1.6 on 2023-02-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('nb_points_legume', models.DecimalField(decimal_places=0, max_digits=3)),
                ('nb_points_fruit', models.DecimalField(decimal_places=0, max_digits=3)),
                ('nb_points_fleur', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
