# Generated by Django 4.1.6 on 2023-02-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='groupe',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
            preserve_default=False,
        ),
    ]
